name: Pipeline CI - Laboratorio 1

# Se ejecuta cada vez que ocurre un push al repositorio
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Informacion del repositorio
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Dueno del repositorio: ${{ github.repository_owner }}"
          echo "Usuario que hizo el push: ${{ github.actor }}"

      - name: Rama y commit
        run: |
          echo "Rama actual: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

      - name: Fecha y hora
        run: |
          echo "Fecha y hora actual: $(date)"

      - name: Version de Git
        run: |
          git --version

      - name: Mensaje de exito
        run: |
          echo "El pipeline finalizo con exito"